-- DropForeignKey
ALTER TABLE "ROUTE_ASSIGNMENT" DROP CONSTRAINT "ROUTE_ASSIGNMENT_person_address_id_fkey";

-- DropForeignKey
ALTER TABLE "ROUTE_ASSIGNMENT" DROP CONSTRAINT "ROUTE_ASSIGNMENT_stop_id_fkey";

-- AlterTable
ALTER TABLE "ROUTE" ALTER COLUMN "end_time" DROP NOT NULL;

-- AlterTable
ALTER TABLE "ROUTE_ASSIGNMENT" ALTER COLUMN "stop_id" DROP NOT NULL,
ALTER COLUMN "person_address_id" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "ROUTE_ASSIGNMENT" ADD CONSTRAINT "ROUTE_ASSIGNMENT_stop_id_fkey" FOREIGN KEY ("stop_id") REFERENCES "STOP"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROUTE_ASSIGNMENT" ADD CONSTRAINT "ROUTE_ASSIGNMENT_person_address_id_fkey" FOREIGN KEY ("person_address_id") REFERENCES "PERSON_ADDRESS"("id") ON DELETE SET NULL ON UPDATE CASCADE;
